version: '3.8'
services:
  iot-service:
    container_name: iot-service-1
    build:
      context: ./
    image: iot-service-1
    ports:
      - "9000:9000"
      - "1883:1883"
    depends_on:
      influxdb:
        condition: service_healthy
      db:
        condition: service_healthy
    links:
      - db
      - influxdb
    env_file:
      - env/server
    volumes:
      - ./email_service_config:/app/email_service_config
      - ./users-initialization:/app/users-initialization
      - ./neutralization-device-stabilization-time:/app/neutralization-device-stabilization-time
  influxdb:
    image: influxdb:2.7.1-alpine
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - $PWD/data:/var/lib/influxdb2
      - $PWD/config:/etc/influxdb2
    env_file:
      - env/influx
  db:
    container_name: db
    hostname: db
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql/create.sql:/docker-entrypoint-initdb.d/create.sql
    env_file:
      - env/postgres
volumes:
  db-data:
    driver: local
  influxdb:
    driver: local