version: '3.8'
services:
  iot-service:
    container_name: iot-service-1
    build:
      context: ./
    image: iot-service-1
    ports:
      - "9000:9000"
    depends_on:
      influxdb:
        condition: service_healthy
      postgresdb:
        condition: service_healthy
    links:
      - postgresdb
      - influxdb
      - hivemq
    env_file:
      - env/server
    volumes:
      - ./email_service_config:/app/email_service_config
      - ./users-initialization.txt:/app/users-initialization.txt
      - ./neutralization-device-stabilization-time.txt:/app/neutralization-device-stabilization-time.txt
      - ./sensor-thresholds.txt:/app/sensor-thresholds.txt
  influxdb:
    image: influxdb:2.7.1-alpine
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - $PWD/data:/var/lib/influxdb2
      - $PWD/config:/etc/influxdb2
    env_file:
      - env/influx
  postgresdb:
    container_name: postgresdb
    hostname: localhost
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
      - ./sql/create.sql:/docker-entrypoint-initdb.d/create.sql
    env_file:
      - env/postgres
  hivemq:
    container_name: hivemq
    image: hivemq/hivemq-ce
    restart: always
    ports:
      - "1883:1883" # MQTT port
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1883" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgresdb-data:
    driver: local
  influxdb:
    driver: local