version: '3.8'
services:
  app:
    image: app:app
    container_name: app
    build:
      context: ../../frontend
    ports:
      - "8080:8080"
    environment:
      - API_PROXY_TARGET=http://host.docker.internal:9000/
  iot-service:
    container_name: iot-service-1
    build:
      context: ./
    image: iot-service-1
    ports:
      - "9000:9000"
    environment:
      - DB_POSTGRES_IOT_SYSTEM_TEST=jdbc:postgresql://dbtest:5432/iot_system_test?user=postgres&password=pass
      - DB_POSTGRES_IOT_SYSTEM=jdbc:postgresql://db:5432/iot_system?user=postgres&password=pass
      - INFLUX_TOKEN=PdcXvj4L8hAq42SNFy5t3FGKi-bEX3UcVU4MjPUHnWcg_ZXUkJsC_-0EkyhvzAH59sdEap9LgpksRxw_3NplUA==
      - SENDER_EMAIL=testsubjectforiotproject@gmail.com
      - SENDER_PASS=hesazkbnzoiahyaw
    depends_on:
      db:
        condition: service_healthy
      dbtest:
        condition: service_healthy
    links:
      - db
      - dbtest
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
  db:
    container_name: db
    hostname: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=iot_system
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/sql/create.sql:/docker-entrypoint-initdb.d/create.sql
  dbtest:
    container_name: dbtest
    hostname: dbtest
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=iot_system_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data-test:/var/lib/postgresql/data
      - ./src/sql/create.sql:/docker-entrypoint-initdb.d/create.sql
volumes:
  db-data:
    driver: local
  db-data-test:
    driver: local
  influxdb:
    driver: local

